---
# Install the packages for apt based OS

- name: Print install welcome msg
  debug:
     msg: "Installing for apt based platforms ..."

- name: printing - scale_install_all_pkgs
  debug:
    msg: "{{ scale_install_all_pkgs }}"
    
- name: printing - scale_install_license_pkgs
  debug:
    msg: "{{ scale_install_license_pkgs }}"

- name: install | Initialize local list
  set_fact:
    local_all_pkgs: []

- name: build up a new pkglist based on the 
  set_fact:
     local_all_pkgs: "{{ local_all_pkgs }} + [ '{{ item | basename }}' ]"
  with_items:
    - " {{ scale_install_all_pkgs }}"
  
- name: VKHU_DEBUG print out new pkglist
  debug: 
    var: local_all_pkgs
    
#
# Install or update GPFS packages
#
- name: Install the GPFS packages
  block:
    - name: install | Install GPFS DPKGs
      apt:
        name: "{{ local_all_pkgs }}"
        state: present
      register: scale_install_result
      
    - name: install | Install GPFS License DPKGs
      apt:
        deb: [ "{{ scale_install_license_pkgs }}" ]
        state: present
      register: scale_install_license_result

    - name: install | Check if GPFS packages were updated
      set_fact:
        scale_install_updated: true
      when:
        - (scale_install_result.changed) 
        #- (scale_install_license_result.changed) or (scale_install_license_dnfresult.changed)
  when: not scale_daemon_running
