---
# Install the packages for apt based OS

- name: Print install welcome msg
  debug:
     msg: "Installing for apt based platforms ..."

- name: printing - scale_install_all_pkgs
  debug:
    msg: "{{ scale_install_all_pkgs }}"
    
- name: printing - scale_install_license_pkgs
  debug:
    msg: "{{ scale_install_license_pkgs }}"
    
#
# Install or update GPFS packages
#
- name: Install the GPFS packages
  block:
    - name: install | Install GPFS DPKGs
      apt:
        name: "{{ item | basename }}"
        state: present
      register: scale_install_result
      with_items:
        - "{{ scale_install_all_pkgs }}"
      
    - name: install | Install GPFS License DPKGs
      apt:
        deb: [ "{{ scale_install_license_pkgs }}" ]
        state: present
      register: scale_install_license_result

    - name: install | Check if GPFS packages were updated
      set_fact:
        scale_install_updated: true
      when:
        - (scale_install_result.changed) 
        #- (scale_install_license_result.changed) or (scale_install_license_dnfresult.changed)
  when: not scale_daemon_running
