---

- name: "Welcome to apt"
  debug:
    msg: "Welcome to apt!"

- name: set the pkgdir fact
  set_fact:
     scale_install_gpfs_pkgdir_name: "{{ gpfs_path }}/gpfs_debs"

- name: install | Stat extracted packages
  stat:
    path: "{{ scale_install_gpfs_pkgdir_name }}"
  register: scale_install_gpfs_pkgdir

- name: VKHU_DEBUG - print out the pkgdir
  debug:
    msg: "{{ scale_install_gpfs_pkgdir }}"

# Set the ansible_archtecture 
- name: Get the debian architecture
  shell: dpkg --print-architecture
  register: deb_arch

- name: Set scale_architecture to deb_arch
  set_fact:
    scale_architecture: "{{ deb_arch.stdout }}"