---
# Local license package installation method

#
# Find GPFS BASE
#
- name: install | Find GPFS License (gpfs.license) Packages
  find:
    paths: "{{ scale_install_gpfs_pkgdir_name }}"
    patterns: gpfs.license*{{ scale_architecture }}*
  register: scale_install_gpfs_license

- name: install | Check valid GPFS License (gpfs.license) Packages
  assert:
    that: scale_install_gpfs_license.matched > 0
    msg: >-
      No GPFS License (gpfs.license) packages found in {{ scale_install_gpfs_pkgdir_name }}/

- name: install | Check valid only one GPFS License (gpfs.license) Packages
  assert:
    that:
      - scale_install_gpfs_license.matched > 0
      - scale_install_gpfs_license.matched == 1
    msg: >-
      More than one GPFS License (gpfs.license) package found in {{ scale_install_gpfs_pkgdir_name }}/

- name: install | Find GPFS License Package
  vars:
    gpfs_license_pkg: "{{ scale_install_gpfs_license.files.0.path | basename }}"
  set_fact:
    scale_gpfs_license_pkg: "{{ gpfs_license_pkg }}"
  
#
# Find GPFS adv packgae
#
- name: install | Find GPFS Advance (gpfs.adv) Package
  find:
    paths: "{{ scale_install_gpfs_pkgdir_name }}"
    patterns: gpfs.adv*.{{ scale_architecture }}*
  register: scale_install_gpfs_adv
  when: '"gpfs.license.std" not in scale_gpfs_license_pkg'


#
# Find GPFS crypto packgae
#
- name: install | Find GPFS crypto (gpfs.crypto) Package
  find:
    paths: "{{ scale_install_gpfs_pkgdir_name }}"
    patterns: gpfs.crypto*.{{ scale_architecture }}*
  register: scale_install_gpfs_crypto
  when: '"gpfs.license.std" not in scale_gpfs_license_pkg'


#
# Add GPFS RPMs
#
- name: install | Add GPFS License Packages to list
  vars:
    current_pkg: "{{ scale_install_gpfs_pkgdir_name }}/{{ item }}"
  set_fact:
    scale_install_license_pkgs: "{{ scale_install_license_pkgs + [ current_pkg ] }}"
  with_items:
    - "{{ scale_install_gpfs_license.files.0.path | basename  }}"

#
# Add GPFS RPMs
#
- name: install | Add GPFS Dependent License RPMs to list
  vars:
    license_pkg: "{{ scale_install_gpfs_license.files.0.path | basename }}"
    current_pkg: /usr/lpp/mmfs/{{ scale_version }}/gpfs_rpms/{{ item }}.rpm
  set_fact:
    scale_install_license_pkgs: "{{ scale_install_license_pkgs + [ current_pkg ] }}"
  with_items:
    - "{{ scale_install_gpfs_adv.files.0.path | basename  }}"
    - "{{ scale_install_gpfs_crypto.files.0.path | basename  }}"
  when: '"gpfs.license.std" not in scale_gpfs_license_pkg'
