---
# Configure IBM Spectrum Scale (GPFS)

- name: cluster | resolve OS dependencies for this role 
  include_tasks: yum/install.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- import_tasks: cluster.yml
  tags: cluster

- import_tasks: config.yml
  tags: config

- import_tasks: cluster_start.yml
  tags: cluster

- import_tasks: storage.yml
  tags: storage

- import_tasks: finalize.yml
  tags: always
