---
# Configure IBM Spectrum Scale (GPFS)

- import_tasks: check.yml
  tags: always

- import_tasks: cluster.yml
  tags: cluster

- import_tasks: config.yml
  tags: config

- import_tasks: cluster_start.yml
  tags: cluster

- import_tasks: storage.yml
  tags: storage

- import_tasks: finalize.yml
  tags: always

  # remote mount functions
- import_tasks: remote_mount/owning.yml
  tags: [never, remote_mount_owning]
  run_once: true
  delegate_to: "{{ groups['owning'].0 }}"

- import_tasks: remote_mount/access.yml
  tags: [never, remote_mount_access]
  run_once: true
  delegate_to: "{{ groups['access'].0 }}"

# cluster node remover playbook
- import_tasks: removenode.yml
  tags: removenode
