---
#
# samples/playbook_storage.yml
#

# Playbook sample for deploying IBM Spectrum Scale (GPFS) cluster with storage
# (NSDs) and file systems. Additional variables need to be defined for this, it
# is recommended to use Ansible group variables for this purpose:
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#assigning-a-variable-to-many-machines-group-variables

# Sample definitions can be found in samples/vars/storage_vars.yml

- hosts: ocp4storage2
  vars:
    - scale_version: 5.1.0.0
    - scale_install_localpkg_path: /root/Spectrum_Scale_Data_Management-5.1.0.0-x86_64-Linux-install
  pre_tasks:
    - include_vars: storage_vars.yml
  roles:
    - core/precheck
    - core/node
    - core/cluster
    - core/postcheck
