---
- import_tasks: yum/install.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
# - import_tasks: apt/install.yml
#   when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
