---
- name: Converge
  hosts: all
  vars:
    scale_version: "{{ lookup('env', 'MY_SCALE_VERSION') }}"
  tasks:
    - name: "Include dependency roles"
      include_role:
        - name: "precheck"
        - name: "node"
