---
- name: Converge
  hosts: all
  vars:
    scale_version: "{{ lookup('env', 'MY_SCALE_VERSION') }}"
  tasks:
    - name: "Include precheck roles"
      include_role:
        name: "precheck"
    - name: "Include node role" 
      include_role:
        name: "node"
