---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
#  ansible-lint
#  flake8
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    # pre_build_image: true
provisioner:
  name: ansible
  env:
    # Allow an command line override the following variables to molecule
    MOL_SCALE_VERSION: '${SCALE_VERSION:-"4.1.1.0"}'
    MOL_RUN_SCALE_CMDS: '${RUN_SCALE_CMDS:-"true"}'
verifier:
  name: ansible
