---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  env:
    # Allow an command line override to provide SCALE_VERSION to molecule
    MOL_SCALE_VERSION: '${SCALE_VERSION:-"4.1.1.0"}'
verifier:
  name: ansible
