---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: debian
    image: docker.io/pycontribs/debian
    pre_build_image: true
provisioner:
  name: ansible
  env:
    MY_SCALE_VERSION: '${SCALE_VERSION:-"4.1.1.0"}'
verifier:
  name: ansible
